# Generated by Django 3.1.2 on 2022-06-13 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'felicitaciones']])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('representante', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('dia', models.IntegerField(choices=[[0, 'Jueves'], [1, 'Viernes']])),
                ('fecha_nacimiento', models.DateField()),
                ('comuna', models.CharField(max_length=50)),
                ('lateralidad', models.IntegerField(choices=[[0, 'DIESTRO'], [1, 'ZURDO']])),
            ],
            options={
                'verbose_name': 'Solicitud de clase',
                'verbose_name_plural': 'Solicitudes clases de golf',
            },
        ),
        migrations.CreateModel(
            name='RegistroReparacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('fecha_recepcion', models.DateField()),
                ('fecha_entrega', models.DateField()),
            ],
            options={
                'verbose_name': 'Registro de reparación',
                'verbose_name_plural': 'Registro de reparaciones',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio_compra', models.IntegerField(verbose_name='Precio unidad')),
                ('precio_venta', models.IntegerField()),
                ('fecha_recepcion', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='productos')),
                ('cantidad', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Reserva.categoriaproducto')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Reserva.marca')),
            ],
        ),
    ]
